config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  resources :jobs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if params[:order] == 'filter'
      @jobs = Job.all.order('temp DESC')
    else
      @jobs = Job.all
    end

    @jobs.each do |job|
      Rails.cache.fetch("#{job.id}/apirequest", expires_in: 1.hours) do
        helpers.getWeatherApi job: job
      end
    end
  end

  def show
    @job = Job.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
    require 'net/http'
    require 'json'
  
    def getWeatherApi job:
        if ((!job.zip || job.zip == 0) && (!job.latitude || !job.longitude))
            job.temp = 0
            job.tempfeels= 0
            job.iconurl= ""
            job.icondescription= "No data to search"
            job.save
        else
            if !job.zip || job.zip == 0
                usezipcode = false
                lat = job.latitude.to_s
                lon = job.longitude.to_s
            else
                zipcode = job.zip.to_s
                usezipcode = true
            end

            if usezipcode
                #@url = 'http://pro.openweathermap.org/data/2.5/forecast/hourly?zip=' + zipcode +',be&appid=43bb4fa1cc59a75e17fb98efe3b4434e'
                @url = 'https://api.weatherbit.io/v2.0/current?&postal_code=' + zipcode + '&country=BE&key='+'f7120113262d41e49dd2445d132d08a1'+'&include=minutely'
            else            
                #@url ='http://pro.openweathermap.org/data/2.5/forecast/hourly?lat=' + lat +'&lon=' + lon + '&appid=43bb4fa1cc59a75e17fb98efe3b4434e'
                @url = 'https://api.weatherbit.io/v2.0/current?&lat=' + lat +'&lon=' + lon + '&key=' + 'f7120113262d41e49dd2445d132d08a1' + '&include=minutely'
            end

            @uri = URI(@url)
        
            @response = Net::HTTP.get @uri
            @output = JSON.parse @response
        
            if !@output || @output.empty? || @output['count'] == 0
                temp = 0
                tempfeels = 0
                iconurl = ''
                icondescription = "Error api call"
            else
                temp = @output['data'][0]['temp']
                tempfeels= @output['data'][0]['app_temp']
                iconurl='https://www.weatherbit.io/static/img/icons/' + @output['data'][0]['weather']['icon'] + '.png'
                icondescription= @output['data'][0]['weather']['description']
            end
            
            job.temp = temp
            job.tempfeels= tempfeels
            job.iconurl=iconurl
            job.icondescription= icondescription
            job.save
        end
    end
end

app/views/jobs/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "ListMinut", root_path, class:"navbar-brand" %>
  </div>
</nav>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<p>Sort by: 
    <%= link_to "Weather", jobs_path(order: 'filter') %>
</p>

<div class="col-12 col-offset-2 ">
    <div class="row justify-content-center">
      <% @jobs.each do |job| %>
            <div class="card" style="margin-bottom: 10px; width: 20rem">
                <div class="row justify-content-center">
                    <h5 class="col-8 ">
                        <%= link_to job.title, job %>
                    </h5>
                    <img class="card-img col-2 mt-1" style="width:20px; height: 20px" <%= image_tag("leaf.png", :alt => "Can't access assets") %>
                </div>
                <hr>

                <div class="card-body">
                    <h5 class="card-title">
                        <%= job.user %>
                    </h5>

                    <p class="card-text">
                        Weather : <%= job.temp%> °C, feels like : <%= job.tempfeels%> °C
                    </p>  
                    <img src="<%= job.iconurl%>" alt= "<%= job.icondescription%>">                
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/jobs/show.html.erb
<div class="container mt-5 border border-warning">
    <div class="row col-12">
        <h1>
            <%= @job.title %>
        </h1>
    </div>
    <div class="row col-12 pl-0 d-flex">
        <div class="col-8 mr-5 border-right border-success mt-2">
            <p>
                <%= @job.description %>
            </p>
        </div>

        <div class="col-2 mt-2">
            <p class="row col-12"> USER :
                <%= @job.user %>

            </p>
            <p class="row col-12"> ZIP CODE :
                <%= @job.zip %>
            </p>
        </div>
    </div>
    <div class="row col-8 justify-content-end" style ="align-items: center">
        <p class="mr-5">
            Weather :
            <%= @job.temp%> °C, feels like : <%= @job.tempfeels%> °C
        </p>
        <img src="<%= @job.iconurl%>" alt="<%= @job.icondescription%>">
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListMinut</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'jobs/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>